const fs = require('fs');
const path = require('path');

// Authoritative summary and city data from Metro-LIST.xlsx
const CITIES_METADATA = [
  { id: 'agra', name: 'Agra', hindiName: 'आगरा', state: 'Uttar Pradesh', systemName: 'Agra Metro (UPMRC)', operator: 'Uttar Pradesh Metro Rail Corporation', activeLines: 1, totalStations: 6, interchanges: 0, establishedYear: 2024, networkLengthKm: 5.2, dailyRidership: '15,000+', centerCoordinates: [27.1767, 78.0081], pdfPage: '1' },
  { id: 'ahmedabad', name: 'Ahmedabad', hindiName: 'अहमदाबाद', state: 'Gujarat', systemName: 'Ahmedabad Metro (GMRC)', operator: 'Gujarat Metro Rail Corporation', activeLines: 4, totalStations: 57, interchanges: 3, establishedYear: 2019, networkLengthKm: 40.03, dailyRidership: '130,000+', centerCoordinates: [23.0225, 72.5714], pdfPage: '4' },
  { id: 'pune', name: 'Pune', hindiName: 'पुणे', state: 'Maharashtra', systemName: 'Pune Metro (Maha Metro)', operator: 'Maharashtra Metro Rail Corporation Limited', activeLines: 2, totalStations: 30, interchanges: 1, establishedYear: 2022, networkLengthKm: 33.2, dailyRidership: '140,000+', centerCoordinates: [18.5204, 73.8567], pdfPage: '7' },
  { id: 'patna', name: 'Patna', hindiName: 'पटना', state: 'Bihar', systemName: 'Patna Metro (PMRC)', operator: 'Patna Metro Rail Corporation', activeLines: 1, totalStations: 3, interchanges: 0, establishedYear: 2025, networkLengthKm: 3.5, dailyRidership: '10,000+', centerCoordinates: [25.5941, 85.1376], pdfPage: '11' },
  { id: 'noida', name: 'Noida', hindiName: 'नोएडा', state: 'Uttar Pradesh', systemName: 'Noida Metro (NMRC)', operator: 'Noida Metro Rail Corporation', activeLines: 1, totalStations: 22, interchanges: 0, establishedYear: 2019, networkLengthKm: 29.7, dailyRidership: '60,000+', centerCoordinates: [28.5355, 77.3910], pdfPage: '12' },
  { id: 'navi-mumbai', name: 'Navi Mumbai', hindiName: 'नवी मुंबई', state: 'Maharashtra', systemName: 'Navi Mumbai Metro (CIDCO / Maha Metro)', operator: 'City and Industrial Development Corporation (CIDCO)', activeLines: 1, totalStations: 11, interchanges: 0, establishedYear: 2023, networkLengthKm: 11.1, dailyRidership: '30,000+', centerCoordinates: [19.033, 73.0297], pdfPage: '14' },
  { id: 'nagpur', name: 'Nagpur', hindiName: 'नागपुर', state: 'Maharashtra', systemName: 'Nagpur Metro (Maha Metro)', operator: 'Maharashtra Metro Rail Corporation Limited', activeLines: 2, totalStations: 38, interchanges: 1, establishedYear: 2019, networkLengthKm: 38.2, dailyRidership: '95,000+', centerCoordinates: [21.1458, 79.0882], pdfPage: '18' },
  { id: 'mumbai', name: 'Mumbai', hindiName: 'मुंबई', state: 'Maharashtra', systemName: 'Mumbai Metro (MMRDA / MMMOCL)', operator: 'Maha Mumbai Metro Operations Corporation', activeLines: 4, totalStations: 74, interchanges: 2, establishedYear: 2014, networkLengthKm: 59.1, dailyRidership: '1.2+ Million', centerCoordinates: [19.076, 72.8777], pdfPage: '19' },
  { id: 'lucknow', name: 'Lucknow', hindiName: 'लखनऊ', state: 'Uttar Pradesh', systemName: 'Lucknow Metro (UPMRC)', operator: 'Uttar Pradesh Metro Rail Corporation', activeLines: 1, totalStations: 21, interchanges: 0, establishedYear: 2017, networkLengthKm: 22.87, dailyRidership: '85,000+', centerCoordinates: [26.8467, 80.9462], pdfPage: '26' },
  { id: 'kolkata', name: 'Kolkata', hindiName: 'कोलकाता', state: 'West Bengal', systemName: 'Kolkata Metro (Metro Railway / KMRCL)', operator: 'Ministry of Railways (Metro Railway Kolkata)', activeLines: 5, totalStations: 58, interchanges: 3, establishedYear: 1984, networkLengthKm: 59.4, dailyRidership: '750,000+', centerCoordinates: [22.5726, 88.3639], pdfPage: '28' },
  { id: 'kochi', name: 'Kochi', hindiName: 'कोच्चि', state: 'Kerala', systemName: 'Kochi Metro (KMRL)', operator: 'Kochi Metro Rail Limited', activeLines: 1, totalStations: 25, interchanges: 0, establishedYear: 2017, networkLengthKm: 28.1, dailyRidership: '100,000+', centerCoordinates: [9.9312, 76.2673], pdfPage: '33' },
  { id: 'kanpur', name: 'Kanpur', hindiName: 'कानपुर', state: 'Uttar Pradesh', systemName: 'Kanpur Metro (UPMRC)', operator: 'Uttar Pradesh Metro Rail Corporation', activeLines: 1, totalStations: 14, interchanges: 0, establishedYear: 2021, networkLengthKm: 16.0, dailyRidership: '35,000+', centerCoordinates: [26.4499, 80.3319], pdfPage: '37' },
  { id: 'jaipur', name: 'Jaipur', hindiName: 'जयपुर', state: 'Rajasthan', systemName: 'Jaipur Metro (JMRC)', operator: 'Jaipur Metro Rail Corporation', activeLines: 1, totalStations: 11, interchanges: 0, establishedYear: 2015, networkLengthKm: 12.0, dailyRidership: '60,000+', centerCoordinates: [26.9124, 75.7873], pdfPage: '40' },
  { id: 'indore', name: 'Indore', hindiName: 'इंदौर', state: 'Madhya Pradesh', systemName: 'Indore Metro (MPMRCL)', operator: 'Madhya Pradesh Metro Rail Corporation Limited', activeLines: 1, totalStations: 5, interchanges: 0, establishedYear: 2024, networkLengthKm: 5.9, dailyRidership: '20,000+', centerCoordinates: [22.7196, 75.8577], pdfPage: '42' },
  { id: 'hyderabad', name: 'Hyderabad', hindiName: 'हैदराबाद', state: 'Telangana', systemName: 'Hyderabad Metro (HMRL / L&T)', operator: 'L&T Metro Rail (Hyderabad) Limited', activeLines: 3, totalStations: 59, interchanges: 3, establishedYear: 2017, networkLengthKm: 69.2, dailyRidership: '520,000+', centerCoordinates: [17.385, 78.4867], pdfPage: '46' },
  { id: 'gurgaon', name: 'Gurgaon', hindiName: 'गुड़गांव', state: 'Haryana', systemName: 'Gurgaon Rapid Metro (DMRC / RMGL)', operator: 'Delhi Metro Rail Corporation', activeLines: 1, totalStations: 11, interchanges: 0, establishedYear: 2013, networkLengthKm: 12.15, dailyRidership: '75,000+', centerCoordinates: [28.4595, 77.0266], pdfPage: '47' },
  { id: 'chennai', name: 'Chennai', hindiName: 'चेन्नई', state: 'Tamil Nadu', systemName: 'Chennai Metro (CMRL)', operator: 'Chennai Metro Rail Limited', activeLines: 2, totalStations: 43, interchanges: 2, establishedYear: 2015, networkLengthKm: 54.1, dailyRidership: '310,000+', centerCoordinates: [13.0827, 80.2707], pdfPage: '60' },
  { id: 'bengaluru', name: 'Bengaluru', hindiName: 'बेंगलुरु', state: 'Karnataka', systemName: 'Namma Metro (BMRCL)', operator: 'Bangalore Metro Rail Corporation Limited', activeLines: 3, totalStations: 85, interchanges: 2, establishedYear: 2011, networkLengthKm: 73.8, dailyRidership: '850,000+', centerCoordinates: [12.9716, 77.5946], pdfPage: '67' },
  { id: 'delhi', name: 'Delhi', hindiName: 'दिल्ली', state: 'Delhi / Haryana / Uttar Pradesh', systemName: 'Delhi Metro (DMRC)', operator: 'Delhi Metro Rail Corporation', activeLines: 12, totalStations: 327, interchanges: 23, establishedYear: 2002, networkLengthKm: 393.1, dailyRidership: '6.0+ Million', centerCoordinates: [28.6139, 77.209], pdfPage: '57' },
  { id: 'bhopal', name: 'Bhopal', hindiName: 'भोपाल', state: 'Madhya Pradesh', systemName: 'Bhopal Metro (Bhoj Metro / MPMRCL)', operator: 'Madhya Pradesh Metro Rail Corporation Limited', activeLines: 2, totalStations: 29, interchanges: 1, establishedYear: 2024, networkLengthKm: 27.87, dailyRidership: '25,000+', centerCoordinates: [23.2599, 77.4126], pdfPage: '5502.jpg' },
  { id: 'meerut', name: 'Meerut', hindiName: 'मेरठ', state: 'Uttar Pradesh', systemName: 'Meerut Metro (NCRTC)', operator: 'National Capital Region Transport Corporation (NCRTC)', activeLines: 1, totalStations: 12, interchanges: 4, establishedYear: 2024, networkLengthKm: 23.6, dailyRidership: '40,000+', centerCoordinates: [28.9845, 77.7064], pdfPage: '5499/5500/5501.jpg' },
];

console.log("Metadata configured for 21 cities.");
